name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: |
        npm ci --prefix frontend
        npm ci --prefix backend
    
    - name: Build Frontend
      run: npm run build --prefix frontend
      env:
        CI: false
    
    - name: Prepare Netlify Deploy
      run: |
        mkdir -p netlify/functions
        cp -r backend/* netlify/functions/
        cp -r frontend/build/* netlify/
    
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './netlify'
        production-branch: main
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
